name: tourman
version: '1.0.0'

services:
  api:
    container_name: api
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    restart: always
    networks:
      - tournet
    volumes:
      - .:/home/app
      - /home/app/node_modules
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: database
    image: mongo
    volumes:
      - mongo-data:/data/db
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - tournet
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  mongo-data:
    driver: local
networks:
  tournet:
